### ISSUE TITLE
Thoughts about the naming of this repo

### ISSUE THREAD

**Issue by marinasundstrom** [garyexplains/piccolo_os_v1#1]
I think that "piccolo-os" would be a more pleasing name for this repo. That is the convention I'm used to. 🙂 

And I don't know why included the version number in the name. You would just tag the releases.

Thank you for this project 🙂 I will dive into it, and see if I might be able to contribute.

**Comment by saburch** [comment]
I agree with @robertsundstrom 
**piccolo-os** sounds much more 'domesticated'

**Comment by garyexplains** [comment]
I have included the version number to distinguish it from a potential piccolo_os_v2. While tags etc can be used I want people to be able to access this without much git knowledge as a simple, easy to access, repo.

As for the name I am more used to _ than -

**Comment by robertsundstrom** [comment]
I realize that you are seeing it more as an educational project.

So you mean that are going to fork the next version into its own repo?

Why not just use branches for past versions?

You should not assume that people would not learn the basic commands of Git. 

I see the potential in this project. Not to build a full OS, but to involve a community to build something useful. 🙂

**Comment by garyexplains** [comment]
If the community shows interest in developing this further then I will create another repo and start proper development there with tags, branches, whatever.

This one needs to be as accessible as possible without someone needing to understand Git. I want as few barriers as possible.
